// import '@fabriq/plugins/laravel-echo'
import '@fabriq/plugins/toast'
import '@fabriq/plugins/v-calendar'
import '@fabriq/plugins/v-mask'
import '@fabriq/plugins/v-tooltip'
import '@fabriq/plugins/vee-validate'
import '@fabriq/plugins/vue-final-modal'
// import '@fabriq/plugins/vue-nestable'
import '@fabriq/plugins/font-awesome'
import '@fabriq/plugins/vue-select'
import '@fabriq/plugins/vue-slide-up-down'

